### ISSUE TITLE
Juste pour accéder au beatmap osu!

### ISSUE THREAD

**Issue by Bibou1494** [ThePooN/bancho.js#30]
Bonjour(ou bonsoir) je voudrais de l'aide pour accéder au beatmap osu! car je voulais faire un random map request. J'ai fait une clé api si besoin. du coup pour savoir comment l'inclure voici mon code
```
const Banchojs = require("bancho.js");

const USERNAME = "username"
const PASSWORD = "IRC password"
const API = "api key"

const client = new Banchojs.BanchoClient({
  username: USERNAME,
  password: PASSWORD
});

const prefix = "!";

const startOsuBot = async () => {
  try {
    await client.connect();
    console.log("osu!Bancho Connected...");

    client.on("PM", async ({ message, user }) => {
      //Check if message was sent by ourselves
      if (user.ircUsername === USERNAME) return;

      //Check for message prefix
      if (message[0] !== "!") return;

      const command = message.split(" ")[0].toLowerCase();

      switch (command) {
                case prefix + "help":
          return await user.sendMessage(`All command are in [https://github.com/Bibou1494/BibouOsu-Bancho-Bot GitHub]`);
    });

  } catch (err) {
    console.error(err);
  }
};

startOsuBot();
```
Merci en avance.
Au revoir.

**Comment by ThePooN** [comment]
Hey,

This library only interfaces with Bancho, osu!stable's chat and multi-player server component.

Fetching beatmaps is thus out-of-scope of this project. You can interface with [APIv1](https://github.com/ppy/osu-api/wiki) or [APIv2](https://osu.ppy.sh/docs/) in order to fetch beatmaps.
APIv1 is easier and probably fits your needs. You can fetch data using simple HTTP requests or use a library like [nodesu](https://npmjs.com/packages/nodesu).

If you need any support, feel free to join [my Discord server](https://discord.gg/ThePooN) and visit #banchojs.

**Comment by Bibou1494** [comment]
Ok thanks anyway
